name: Deploy
on:
  push:
    branches:
      - main
jobs:
  setup:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make env
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_NAME: "main"
          file_name: .env
          fail_on_empty: true
      - name: install dependency
        run: npm i
      - name: build
        run: npm run build 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: copy
        run: aws s3 sync build/ s3://tests-static-ronal-web
      

        