name: Deploy

on:
  push:
    branches:
      - main
      - dev
      - prod

jobs:
  setup:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Environment Variable
        run: |
          if [ $GITHUB_REF == 'refs/heads/main' ]; then
            echo "REACT_APP_NAME=main" >> .env
            S3_BUCKET_NAME="tests-static-ronal-web"
          elif [ $GITHUB_REF == 'refs/heads/dev' ]; then
            echo "REACT_APP_NAME=dev" >> .env
            S3_BUCKET_NAME="tests-static-ronal-web"
          else
            echo "REACT_APP_NAME=prod" >> .env
            S3_BUCKET_NAME="tests-static-ronal-web"
          fi
          echo "S3_BUCKET_NAME=$S3_BUCKET_NAME" >> .env
      - name: Install dependency
        run: npm i
      - name: Build
        run: npm run build 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Copy to S3
        run: aws s3 sync build/ s3://$S3_BUCKET_NAME
