name: Deploy

on:
  push:
    branches:
      - main
      - dev
      - prod

jobs:
  setup:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Environment Variable
        run: |
          if [ $GITHUB_REF == 'refs/heads/main' ]; then
            echo "REACT_APP_NAME=main" >> $GITHUB_ENV
            echo "S3_BUCKET_NAME=tests-static-ronal-web" >> $GITHUB_ENV
          elif [ $GITHUB_REF == 'refs/heads/dev' ]; then
            echo "REACT_APP_NAME=develop" >> $GITHUB_ENV
            echo "S3_BUCKET_NAME=tests-static-ronal-web" >> $GITHUB_ENV
          else
            echo "REACT_APP_NAME=prod" >> $GITHUB_ENV
            echo "S3_BUCKET_NAME=tests-static-ronal-web" >> $GITHUB_ENV
          fi
      - name: Install dependency
        run: npm i
      - name: Build
        run: npm run build 
     #- name: Configure AWS Credentials
      #  uses: aws-actions/configure-aws-credentials@v1
      #  with:
       #   aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       #   aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #  aws-region: us-east-1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::904047573216:role/s3role
          role-session-name: GitHub_SH_Deploy_IAM_to_AWS
          aws-region: us-east-1
          
      - name: Copy to S3
        run: aws s3 sync build/ "s3://${{ env.S3_BUCKET_NAME }}"
